// autogenerated: do not add any changes
#ifndef animation_3d_bone_mask_configuration_h
#define animation_3d_bone_mask_configuration_h
#include "configuration.h"
namespace gb
{
class animation_3d_bone_mask_configuration : public configuration
{
public:
animation_3d_bone_mask_configuration(void) = default;
~animation_3d_bone_mask_configuration(void) = default;
std::string get_bone_name(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_bone_name(std::string bone_name);
#endif
f32 get_weight(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_weight(f32 weight);
#endif
void serialize_xml(pugi::xml_document& document, const std::string& path);
void serialize_json(Json::Value& root);
void serialize_xml(pugi::xml_document& document, pugi::xpath_node& node);
};
};
#endif
