// autogenerated: do not add any changes
#ifndef animation_configuration_h
#define animation_configuration_h
#include "configuration.h"
namespace gb
{
class animation_configuration : public configuration
{
public:
animation_configuration(void) = default;
~animation_configuration(void) = default;
std::string get_animation_filename(void) const;
#if defined(__EDITOR__)
void set_animation_filename(std::string filename);
#endif
std::string get_animation_name(void) const;
#if defined(__EDITOR__)
void set_animation_name(std::string name);
#endif
void serialize(pugi::xml_document& document, const std::string& path);
#if defined(__EDITOR__)
void deserialize(pugi::xml_node& node);
#endif
void serialize(pugi::xml_document& document, pugi::xpath_node& node);
};
};
#endif
