// autogenerated: do not add any changes
#include "attachment_configuration.h"
namespace gb
{
std::string attachment_configuration::get_name(void) const
{
const auto& iterator = m_attributes.find("/attachment/name");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void attachment_configuration::set_name(std::string name)
{
configuration::set_attribute("/attachment/name", std::make_shared<configuration_attribute>(name));
}
#endif
ui32 attachment_configuration::get_pixel_format(void) const
{
const auto& iterator = m_attributes.find("/attachment/pixel_format");
assert(iterator != m_attributes.end());
ui32 value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void attachment_configuration::set_pixel_format(ui32 pixel_format)
{
configuration::set_attribute("/attachment/pixel_format", std::make_shared<configuration_attribute>(pixel_format));
}
#endif
f32 attachment_configuration::get_clear_color_r(void) const
{
const auto& iterator = m_attributes.find("/ws_technique/clear_color_r");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void attachment_configuration::set_clear_color_r(f32 clear_color_r)
{
configuration::set_attribute("/ws_technique/clear_color_r", std::make_shared<configuration_attribute>(clear_color_r));
}
#endif
f32 attachment_configuration::get_clear_color_g(void) const
{
const auto& iterator = m_attributes.find("/ws_technique/clear_color_g");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void attachment_configuration::set_clear_color_g(f32 clear_color_g)
{
configuration::set_attribute("/ws_technique/clear_color_g", std::make_shared<configuration_attribute>(clear_color_g));
}
#endif
f32 attachment_configuration::get_clear_color_b(void) const
{
const auto& iterator = m_attributes.find("/ws_technique/clear_color_b");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void attachment_configuration::set_clear_color_b(f32 clear_color_b)
{
configuration::set_attribute("/ws_technique/clear_color_b", std::make_shared<configuration_attribute>(clear_color_b));
}
#endif
f32 attachment_configuration::get_clear_color_a(void) const
{
const auto& iterator = m_attributes.find("/ws_technique/clear_color_a");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void attachment_configuration::set_clear_color_a(f32 clear_color_a)
{
configuration::set_attribute("/ws_technique/clear_color_a", std::make_shared<configuration_attribute>(clear_color_a));
}
#endif
void attachment_configuration::serialize_xml(pugi::xml_document& document, const std::string& path)
{
pugi::xpath_node node;
node = document.select_single_node((path + "/attachment").c_str());
std::string name = node.node().attribute("name").as_string();
configuration::set_attribute("/attachment/name", std::make_shared<configuration_attribute>(name));
ui32 pixel_format = node.node().attribute("pixel_format").as_uint();
configuration::set_attribute("/attachment/pixel_format", std::make_shared<configuration_attribute>(pixel_format));
f32 clear_color_r = node.node().attribute("clear_color_r").as_float();
configuration::set_attribute("/ws_technique/clear_color_r", std::make_shared<configuration_attribute>(clear_color_r));
f32 clear_color_g = node.node().attribute("clear_color_g").as_float();
configuration::set_attribute("/ws_technique/clear_color_g", std::make_shared<configuration_attribute>(clear_color_g));
f32 clear_color_b = node.node().attribute("clear_color_b").as_float();
configuration::set_attribute("/ws_technique/clear_color_b", std::make_shared<configuration_attribute>(clear_color_b));
f32 clear_color_a = node.node().attribute("clear_color_a").as_float();
configuration::set_attribute("/ws_technique/clear_color_a", std::make_shared<configuration_attribute>(clear_color_a));
}
void attachment_configuration::serialize_json(Json::Value& json)
{
std::string name = json.get("name", "unknown").asString();
configuration::set_attribute("/attachment/name", std::make_shared<configuration_attribute>(name));
ui32 pixel_format = json.get("pixel_format", 0).asUInt();
configuration::set_attribute("/attachment/pixel_format", std::make_shared<configuration_attribute>(pixel_format));
f32 clear_color_r = json.get("clear_color_r", 0.f).asFloat();
configuration::set_attribute("/ws_technique/clear_color_r", std::make_shared<configuration_attribute>(clear_color_r));
f32 clear_color_g = json.get("clear_color_g", 0.f).asFloat();
configuration::set_attribute("/ws_technique/clear_color_g", std::make_shared<configuration_attribute>(clear_color_g));
f32 clear_color_b = json.get("clear_color_b", 0.f).asFloat();
configuration::set_attribute("/ws_technique/clear_color_b", std::make_shared<configuration_attribute>(clear_color_b));
f32 clear_color_a = json.get("clear_color_a", 0.f).asFloat();
configuration::set_attribute("/ws_technique/clear_color_a", std::make_shared<configuration_attribute>(clear_color_a));
}
void attachment_configuration::serialize_xml(pugi::xml_document& document, pugi::xpath_node& node)
{
std::string name = node.node().attribute("name").as_string();
configuration::set_attribute("/attachment/name", std::make_shared<configuration_attribute>(name));
ui32 pixel_format = node.node().attribute("pixel_format").as_uint();
configuration::set_attribute("/attachment/pixel_format", std::make_shared<configuration_attribute>(pixel_format));
f32 clear_color_r = node.node().attribute("clear_color_r").as_float();
configuration::set_attribute("/ws_technique/clear_color_r", std::make_shared<configuration_attribute>(clear_color_r));
f32 clear_color_g = node.node().attribute("clear_color_g").as_float();
configuration::set_attribute("/ws_technique/clear_color_g", std::make_shared<configuration_attribute>(clear_color_g));
f32 clear_color_b = node.node().attribute("clear_color_b").as_float();
configuration::set_attribute("/ws_technique/clear_color_b", std::make_shared<configuration_attribute>(clear_color_b));
f32 clear_color_a = node.node().attribute("clear_color_a").as_float();
configuration::set_attribute("/ws_technique/clear_color_a", std::make_shared<configuration_attribute>(clear_color_a));
}
}
