// autogenerated: do not add any changes, added changes will be lost.
#ifndef configuration_accessor_h
#define configuration_accessor_h
#include "terrain_configuration.h"
#include "material_configuration.h"
#include "model_configuration.h"
#include "ocean_configuration.h"
#include "output_technique_configuration.h"
#include "particle_emitter_configuration.h"
#include "skybox_configuration.h"
#include "ss_technique_configuration.h"
#include "transition_configuration.h"
#include "ws_technique_configuration.h"
namespace gb
{
class configuration_accessor
{
public:
configuration_accessor(void) = default;
~configuration_accessor(void) = default;
std::shared_ptr<configuration> get_terrain_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_material_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_model_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_ocean_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_output_technique_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_particle_emitter_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_skybox_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_ss_technique_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_transition_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_ws_technique_configuration(const std::string& filename) const;
};
};
#endif
