// autogenerated: do not add any changes
#ifndef custom_mesh_deferred_light_source_3d_configuration_h
#define custom_mesh_deferred_light_source_3d_configuration_h
#include "configuration.h"
#include "material_configuration.h"
namespace gb
{
class custom_mesh_deferred_light_source_3d_configuration : public game_object_configuration
{
public:
custom_mesh_deferred_light_source_3d_configuration(void) = default;
~custom_mesh_deferred_light_source_3d_configuration(void) = default;
f32 get_radius(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_radius(f32 radius);
#endif
f32 get_color_r(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_color_r(f32 color_r);
#endif
f32 get_color_g(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_color_g(f32 color_g);
#endif
f32 get_color_b(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_color_b(f32 color_b);
#endif
std::string get_mesh_filename(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_mesh_filename(std::string mesh_filename);
#endif
std::vector<std::shared_ptr<configuration>> get_materials_configurations(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void add_materials_configurations(const std::shared_ptr<gb::material_configuration>& material);
#endif
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_materials_configurations(const std::shared_ptr<gb::material_configuration>& material, i32 index);
#endif
void serialize_xml(const std::string& filename);
void serialize_json(const std::string& filename);
};
};
#endif
