// autogenerated: do not add any changes
#ifndef output_technique_configuration_h
#define output_technique_configuration_h
#include "configuration.h"
#include "material_configuration.h"
namespace gb
{
class output_technique_configuration : public configuration
{
public:
output_technique_configuration(void) = default;
~output_technique_configuration(void) = default;
std::string get_guid(void) const;
#if defined(__EDITOR__)
void set_guid(std::string guid);
#endif
std::shared_ptr<material_configuration> get_material_configuration(void) const;
#if defined(__EDITOR__)
void set_material_configuration(const std::shared_ptr<gb::material_configuration>& material);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
};
#endif
