// autogenerated: do not add any changes
#include "output_technique_configuration.h"
namespace gb
{
std::string output_technique_configuration::get_guid(void) const
{
const auto& iterator = m_attributes.find("/output_technique/guid");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void output_technique_configuration::set_guid(std::string guid)
{
configuration::set_attribute("/output_technique/guid", std::make_shared<configuration_attribute>(guid));
}
#endif
std::shared_ptr<gb::material_configuration> output_technique_configuration::get_material_configuration(void) const
{
const auto& iterator = m_configurations.find("/output_technique/material");
if(iterator == m_configurations.end())
{
return nullptr;
}
assert(iterator != m_configurations.end());
assert(iterator->second.size() != 0);
return std::static_pointer_cast<gb::material_configuration>(iterator->second.at(0));
}
#if defined(__EDITOR__)
void output_technique_configuration::set_material_configuration(const std::shared_ptr<gb::material_configuration>& material)
{
configuration::set_configuration("/output_technique/material", material, 0);
}
#endif
void output_technique_configuration::serialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml_document(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/output_technique");
std::string guid = node.node().attribute("guid").as_string();
configuration::set_attribute("/output_technique/guid", std::make_shared<configuration_attribute>(guid));
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
pugi::xpath_node material_node = document.select_single_node("/output_technique/material");
material->serialize(material_node.node().attribute("filename").as_string());
configuration::set_configuration("/output_technique/material", material);
}
#if defined(__EDITOR__)
void output_technique_configuration::deserialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = document.load("");
assert(result.status == pugi::status_ok);
pugi::xml_node node = document.append_child("output_technique");
pugi::xml_node parent_node = node;
pugi::xml_attribute attribute;
attribute = node.append_attribute("guid");
std::string guid = output_technique_configuration::get_guid();
attribute.set_value(guid.c_str());
node = parent_node.append_child("material");
attribute = node.append_attribute("filename");
attribute.set_value(configuration::get_filename().c_str());
document.save_file(filename.c_str());
}
#endif
}
