// autogenerated: do not add any changes
#include "particle_emitter_configuration.h"
namespace gb
{
i32 particle_emitter_configuration::get_z_order(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/z_order");
assert(iterator != m_attributes.end());
i32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_z_order(i32 z_order)
{
configuration::set_attribute("/particle_emitter/z_order", std::make_shared<configuration_attribute>(z_order));
}
#endif
ui32 particle_emitter_configuration::get_num_particles(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/num_particles");
assert(iterator != m_attributes.end());
ui32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_num_particles(ui32 num_particles)
{
configuration::set_attribute("/particle_emitter/num_particles", std::make_shared<configuration_attribute>(num_particles));
}
#endif
ui32 particle_emitter_configuration::get_duration(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/duration");
assert(iterator != m_attributes.end());
ui32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_duration(ui32 duration)
{
configuration::set_attribute("/particle_emitter/duration", std::make_shared<configuration_attribute>(duration));
}
#endif
f32 particle_emitter_configuration::get_duration_randomess(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/duration_randomness");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_duration_randomess(f32 duration_randomness)
{
configuration::set_attribute("/particle_emitter/duration_randomness", std::make_shared<configuration_attribute>(duration_randomness));
}
#endif
f32 particle_emitter_configuration::get_velocity_sensitivity(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/velocity_sensitivity");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_velocity_sensitivity(f32 velocity_sensitivity)
{
configuration::set_attribute("/particle_emitter/velocity_sensitivity", std::make_shared<configuration_attribute>(velocity_sensitivity));
}
#endif
f32 particle_emitter_configuration::get_min_horizontal_velocity(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/min_horizontal_velocity");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_min_horizontal_velocity(f32 min_horizontal_velocity)
{
configuration::set_attribute("/particle_emitter/min_horizontal_velocity", std::make_shared<configuration_attribute>(min_horizontal_velocity));
}
#endif
f32 particle_emitter_configuration::get_max_horizontal_velocity(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/max_horizontal_velocity");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_max_horizontal_velocity(f32 max_horizontal_velocity)
{
configuration::set_attribute("/particle_emitter/max_horizontal_velocity", std::make_shared<configuration_attribute>(max_horizontal_velocity));
}
#endif
f32 particle_emitter_configuration::get_min_vertical_velocity(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/min_vertical_velocity");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_min_vertical_velocity(f32 min_vertical_velocity)
{
configuration::set_attribute("/particle_emitter/min_vertical_velocity", std::make_shared<configuration_attribute>(min_vertical_velocity));
}
#endif
f32 particle_emitter_configuration::get_max_vertical_velocity(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/max_vertical_velocity");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_max_vertical_velocity(f32 max_vertical_velocity)
{
configuration::set_attribute("/particle_emitter/max_vertical_velocity", std::make_shared<configuration_attribute>(max_vertical_velocity));
}
#endif
f32 particle_emitter_configuration::get_end_velocity(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/end_velocity");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_end_velocity(f32 end_velocity)
{
configuration::set_attribute("/particle_emitter/end_velocity", std::make_shared<configuration_attribute>(end_velocity));
}
#endif
f32 particle_emitter_configuration::get_gravity_x(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/gravity_x");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_gravity_x(f32 gravity_x)
{
configuration::set_attribute("/particle_emitter/gravity_x", std::make_shared<configuration_attribute>(gravity_x));
}
#endif
f32 particle_emitter_configuration::get_gravity_y(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/gravity_y");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_gravity_y(f32 gravity_y)
{
configuration::set_attribute("/particle_emitter/gravity_y", std::make_shared<configuration_attribute>(gravity_y));
}
#endif
f32 particle_emitter_configuration::get_gravity_z(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/gravity_z");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_gravity_z(f32 gravity_z)
{
configuration::set_attribute("/particle_emitter/gravity_z", std::make_shared<configuration_attribute>(gravity_z));
}
#endif
ui8 particle_emitter_configuration::get_source_color_r(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/source_color_r");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_source_color_r(ui8 source_color_r)
{
configuration::set_attribute("/particle_emitter/source_color_r", std::make_shared<configuration_attribute>(source_color_r));
}
#endif
ui8 particle_emitter_configuration::get_source_color_g(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/source_color_g");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_source_color_g(ui8 source_color_g)
{
configuration::set_attribute("/particle_emitter/source_color_g", std::make_shared<configuration_attribute>(source_color_g));
}
#endif
ui8 particle_emitter_configuration::get_source_color_b(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/source_color_b");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_source_color_b(ui8 source_color_b)
{
configuration::set_attribute("/particle_emitter/source_color_b", std::make_shared<configuration_attribute>(source_color_b));
}
#endif
ui8 particle_emitter_configuration::get_source_color_a(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/source_color_a");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_source_color_a(ui8 source_color_a)
{
configuration::set_attribute("/particle_emitter/source_color_a", std::make_shared<configuration_attribute>(source_color_a));
}
#endif
ui8 particle_emitter_configuration::get_destination_color_r(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/destination_color_r");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_destination_color_r(ui8 destination_color_r)
{
configuration::set_attribute("/particle_emitter/destination_color_r", std::make_shared<configuration_attribute>(destination_color_r));
}
#endif
ui8 particle_emitter_configuration::get_destination_color_g(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/destination_color_g");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_destination_color_g(ui8 destination_color_g)
{
configuration::set_attribute("/particle_emitter/destination_color_g", std::make_shared<configuration_attribute>(destination_color_g));
}
#endif
ui8 particle_emitter_configuration::get_destination_color_b(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/destination_color_b");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_destination_color_b(ui8 destination_color_b)
{
configuration::set_attribute("/particle_emitter/destination_color_b", std::make_shared<configuration_attribute>(destination_color_b));
}
#endif
ui8 particle_emitter_configuration::get_destination_color_a(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/destination_color_a");
assert(iterator != m_attributes.end());
ui8 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_destination_color_a(ui8 destination_color_a)
{
configuration::set_attribute("/particle_emitter/destination_color_a", std::make_shared<configuration_attribute>(destination_color_a));
}
#endif
f32 particle_emitter_configuration::get_source_size_x(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/source_size_x");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_source_size_x(f32 source_size_x)
{
configuration::set_attribute("/particle_emitter/source_size_x", std::make_shared<configuration_attribute>(source_size_x));
}
#endif
f32 particle_emitter_configuration::get_source_size_y(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/source_size_y");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_source_size_y(f32 source_size_y)
{
configuration::set_attribute("/particle_emitter/source_size_y", std::make_shared<configuration_attribute>(source_size_y));
}
#endif
f32 particle_emitter_configuration::get_destination_size_x(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/destination_size_x");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_destination_size_x(f32 destination_size_x)
{
configuration::set_attribute("/particle_emitter/destination_size_x", std::make_shared<configuration_attribute>(destination_size_x));
}
#endif
f32 particle_emitter_configuration::get_destination_size_y(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/destination_size_y");
assert(iterator != m_attributes.end());
f32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_destination_size_y(f32 destination_size_y)
{
configuration::set_attribute("/particle_emitter/destination_size_y", std::make_shared<configuration_attribute>(destination_size_y));
}
#endif
ui32 particle_emitter_configuration::get_min_emitt_interval(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/min_emitt_interval");
assert(iterator != m_attributes.end());
ui32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_min_emitt_interval(ui32 min_emitt_interval)
{
configuration::set_attribute("/particle_emitter/min_emitt_interval", std::make_shared<configuration_attribute>(min_emitt_interval));
}
#endif
ui32 particle_emitter_configuration::get_max_emitt_interval(void) const
{
const auto& iterator = m_attributes.find("/particle_emitter/max_emitt_interval");
assert(iterator != m_attributes.end());
ui32 value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::set_max_emitt_interval(ui32 max_emitt_interval)
{
configuration::set_attribute("/particle_emitter/max_emitt_interval", std::make_shared<configuration_attribute>(max_emitt_interval));
}
#endif
std::vector<std::shared_ptr<configuration>> particle_emitter_configuration::get_materials_configurations(void) const
{
const auto& iterator = m_configurations.find("/particle_emitter/materials/material");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__EDITOR__)
void particle_emitter_configuration::add_materials_configurations(const std::shared_ptr<gb::material_configuration>& material)
{
configuration::set_configuration("/particle_emitter/materials/material", material);
}
#endif
#if defined(__EDITOR__)
void particle_emitter_configuration::set_materials_configurations(const std::shared_ptr<gb::material_configuration>& material, i32 index)
{
configuration::set_configuration("/particle_emitter/materials/material", material, index);
}
#endif
void particle_emitter_configuration::serialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml_document(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/particle_emitter");
i32 z_order = node.node().attribute("z_order").as_int();
configuration::set_attribute("/particle_emitter/z_order", std::make_shared<configuration_attribute>(z_order));
ui32 num_particles = node.node().attribute("num_particles").as_uint();
configuration::set_attribute("/particle_emitter/num_particles", std::make_shared<configuration_attribute>(num_particles));
ui32 duration = node.node().attribute("duration").as_uint();
configuration::set_attribute("/particle_emitter/duration", std::make_shared<configuration_attribute>(duration));
f32 duration_randomness = node.node().attribute("duration_randomness").as_float();
configuration::set_attribute("/particle_emitter/duration_randomness", std::make_shared<configuration_attribute>(duration_randomness));
f32 velocity_sensitivity = node.node().attribute("velocity_sensitivity").as_float();
configuration::set_attribute("/particle_emitter/velocity_sensitivity", std::make_shared<configuration_attribute>(velocity_sensitivity));
f32 min_horizontal_velocity = node.node().attribute("min_horizontal_velocity").as_float();
configuration::set_attribute("/particle_emitter/min_horizontal_velocity", std::make_shared<configuration_attribute>(min_horizontal_velocity));
f32 max_horizontal_velocity = node.node().attribute("max_horizontal_velocity").as_float();
configuration::set_attribute("/particle_emitter/max_horizontal_velocity", std::make_shared<configuration_attribute>(max_horizontal_velocity));
f32 min_vertical_velocity = node.node().attribute("min_vertical_velocity").as_float();
configuration::set_attribute("/particle_emitter/min_vertical_velocity", std::make_shared<configuration_attribute>(min_vertical_velocity));
f32 max_vertical_velocity = node.node().attribute("max_vertical_velocity").as_float();
configuration::set_attribute("/particle_emitter/max_vertical_velocity", std::make_shared<configuration_attribute>(max_vertical_velocity));
f32 end_velocity = node.node().attribute("end_velocity").as_float();
configuration::set_attribute("/particle_emitter/end_velocity", std::make_shared<configuration_attribute>(end_velocity));
f32 gravity_x = node.node().attribute("gravity_x").as_float();
configuration::set_attribute("/particle_emitter/gravity_x", std::make_shared<configuration_attribute>(gravity_x));
f32 gravity_y = node.node().attribute("gravity_y").as_float();
configuration::set_attribute("/particle_emitter/gravity_y", std::make_shared<configuration_attribute>(gravity_y));
f32 gravity_z = node.node().attribute("gravity_z").as_float();
configuration::set_attribute("/particle_emitter/gravity_z", std::make_shared<configuration_attribute>(gravity_z));
ui8 source_color_r = node.node().attribute("source_color_r").as_uint();
configuration::set_attribute("/particle_emitter/source_color_r", std::make_shared<configuration_attribute>(source_color_r));
ui8 source_color_g = node.node().attribute("source_color_g").as_uint();
configuration::set_attribute("/particle_emitter/source_color_g", std::make_shared<configuration_attribute>(source_color_g));
ui8 source_color_b = node.node().attribute("source_color_b").as_uint();
configuration::set_attribute("/particle_emitter/source_color_b", std::make_shared<configuration_attribute>(source_color_b));
ui8 source_color_a = node.node().attribute("source_color_a").as_uint();
configuration::set_attribute("/particle_emitter/source_color_a", std::make_shared<configuration_attribute>(source_color_a));
ui8 destination_color_r = node.node().attribute("destination_color_r").as_uint();
configuration::set_attribute("/particle_emitter/destination_color_r", std::make_shared<configuration_attribute>(destination_color_r));
ui8 destination_color_g = node.node().attribute("destination_color_g").as_uint();
configuration::set_attribute("/particle_emitter/destination_color_g", std::make_shared<configuration_attribute>(destination_color_g));
ui8 destination_color_b = node.node().attribute("destination_color_b").as_uint();
configuration::set_attribute("/particle_emitter/destination_color_b", std::make_shared<configuration_attribute>(destination_color_b));
ui8 destination_color_a = node.node().attribute("destination_color_a").as_uint();
configuration::set_attribute("/particle_emitter/destination_color_a", std::make_shared<configuration_attribute>(destination_color_a));
f32 source_size_x = node.node().attribute("source_size_x").as_float();
configuration::set_attribute("/particle_emitter/source_size_x", std::make_shared<configuration_attribute>(source_size_x));
f32 source_size_y = node.node().attribute("source_size_y").as_float();
configuration::set_attribute("/particle_emitter/source_size_y", std::make_shared<configuration_attribute>(source_size_y));
f32 destination_size_x = node.node().attribute("destination_size_x").as_float();
configuration::set_attribute("/particle_emitter/destination_size_x", std::make_shared<configuration_attribute>(destination_size_x));
f32 destination_size_y = node.node().attribute("destination_size_y").as_float();
configuration::set_attribute("/particle_emitter/destination_size_y", std::make_shared<configuration_attribute>(destination_size_y));
ui32 min_emitt_interval = node.node().attribute("min_emitt_interval").as_uint();
configuration::set_attribute("/particle_emitter/min_emitt_interval", std::make_shared<configuration_attribute>(min_emitt_interval));
ui32 max_emitt_interval = node.node().attribute("max_emitt_interval").as_uint();
configuration::set_attribute("/particle_emitter/max_emitt_interval", std::make_shared<configuration_attribute>(max_emitt_interval));
pugi::xpath_node_set material_nodes = document.select_nodes("/particle_emitter/materials/material");
for (pugi::xpath_node_set::const_iterator iterator = material_nodes.begin(); iterator != material_nodes.end(); ++iterator)
{
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
material->serialize((*iterator).node().attribute("filename").as_string());
configuration::set_configuration("/particle_emitter/materials/material", material);
}
}
#if defined(__EDITOR__)
void particle_emitter_configuration::deserialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = document.load("");
assert(result.status == pugi::status_ok);
pugi::xml_node node = document.append_child("particle_emitter");
pugi::xml_node parent_node = node;
pugi::xml_attribute attribute;
attribute = node.append_attribute("z_order");
i32 z_order = particle_emitter_configuration::get_z_order();
attribute.set_value(z_order);
attribute = node.append_attribute("num_particles");
ui32 num_particles = particle_emitter_configuration::get_num_particles();
attribute.set_value(num_particles);
attribute = node.append_attribute("duration");
ui32 duration = particle_emitter_configuration::get_duration();
attribute.set_value(duration);
attribute = node.append_attribute("duration_randomness");
f32 duration_randomness = particle_emitter_configuration::get_duration_randomess();
attribute.set_value(duration_randomness);
attribute = node.append_attribute("velocity_sensitivity");
f32 velocity_sensitivity = particle_emitter_configuration::get_velocity_sensitivity();
attribute.set_value(velocity_sensitivity);
attribute = node.append_attribute("min_horizontal_velocity");
f32 min_horizontal_velocity = particle_emitter_configuration::get_min_horizontal_velocity();
attribute.set_value(min_horizontal_velocity);
attribute = node.append_attribute("max_horizontal_velocity");
f32 max_horizontal_velocity = particle_emitter_configuration::get_max_horizontal_velocity();
attribute.set_value(max_horizontal_velocity);
attribute = node.append_attribute("min_vertical_velocity");
f32 min_vertical_velocity = particle_emitter_configuration::get_min_vertical_velocity();
attribute.set_value(min_vertical_velocity);
attribute = node.append_attribute("max_vertical_velocity");
f32 max_vertical_velocity = particle_emitter_configuration::get_max_vertical_velocity();
attribute.set_value(max_vertical_velocity);
attribute = node.append_attribute("end_velocity");
f32 end_velocity = particle_emitter_configuration::get_end_velocity();
attribute.set_value(end_velocity);
attribute = node.append_attribute("gravity_x");
f32 gravity_x = particle_emitter_configuration::get_gravity_x();
attribute.set_value(gravity_x);
attribute = node.append_attribute("gravity_y");
f32 gravity_y = particle_emitter_configuration::get_gravity_y();
attribute.set_value(gravity_y);
attribute = node.append_attribute("gravity_z");
f32 gravity_z = particle_emitter_configuration::get_gravity_z();
attribute.set_value(gravity_z);
attribute = node.append_attribute("source_color_r");
ui8 source_color_r = particle_emitter_configuration::get_source_color_r();
attribute.set_value(source_color_r);
attribute = node.append_attribute("source_color_g");
ui8 source_color_g = particle_emitter_configuration::get_source_color_g();
attribute.set_value(source_color_g);
attribute = node.append_attribute("source_color_b");
ui8 source_color_b = particle_emitter_configuration::get_source_color_b();
attribute.set_value(source_color_b);
attribute = node.append_attribute("source_color_a");
ui8 source_color_a = particle_emitter_configuration::get_source_color_a();
attribute.set_value(source_color_a);
attribute = node.append_attribute("destination_color_r");
ui8 destination_color_r = particle_emitter_configuration::get_destination_color_r();
attribute.set_value(destination_color_r);
attribute = node.append_attribute("destination_color_g");
ui8 destination_color_g = particle_emitter_configuration::get_destination_color_g();
attribute.set_value(destination_color_g);
attribute = node.append_attribute("destination_color_b");
ui8 destination_color_b = particle_emitter_configuration::get_destination_color_b();
attribute.set_value(destination_color_b);
attribute = node.append_attribute("destination_color_a");
ui8 destination_color_a = particle_emitter_configuration::get_destination_color_a();
attribute.set_value(destination_color_a);
attribute = node.append_attribute("source_size_x");
f32 source_size_x = particle_emitter_configuration::get_source_size_x();
attribute.set_value(source_size_x);
attribute = node.append_attribute("source_size_y");
f32 source_size_y = particle_emitter_configuration::get_source_size_y();
attribute.set_value(source_size_y);
attribute = node.append_attribute("destination_size_x");
f32 destination_size_x = particle_emitter_configuration::get_destination_size_x();
attribute.set_value(destination_size_x);
attribute = node.append_attribute("destination_size_y");
f32 destination_size_y = particle_emitter_configuration::get_destination_size_y();
attribute.set_value(destination_size_y);
attribute = node.append_attribute("min_emitt_interval");
ui32 min_emitt_interval = particle_emitter_configuration::get_min_emitt_interval();
attribute.set_value(min_emitt_interval);
attribute = node.append_attribute("max_emitt_interval");
ui32 max_emitt_interval = particle_emitter_configuration::get_max_emitt_interval();
attribute.set_value(max_emitt_interval);
node = parent_node.append_child("materials");
for(const auto& iterator : particle_emitter_configuration::get_materials_configurations())
{
std::shared_ptr<gb::material_configuration> configuration = std::static_pointer_cast<gb::material_configuration>(iterator);
pugi::xml_node child_node = node.append_child("material");
attribute = child_node.append_attribute("filename");
attribute.set_value(configuration->get_filename().c_str());
}
document.save_file(filename.c_str());
}
#endif
}
