// autogenerated: do not add any changes
#include "shader_configuration.h"
namespace gb
{
std::string shader_configuration::get_filename(void) const
{
const auto& iterator = m_attributes.find("/shader/filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void shader_configuration::set_filename(std::string filename)
{
configuration::set_attribute("/shader/filename", std::make_shared<configuration_attribute>(filename));
}
#endif
void shader_configuration::serialize(pugi::xml_document& document, const std::string& path)
{
pugi::xpath_node node;
node = document.select_single_node((path + "/shader").c_str());
std::string filename = node.node().attribute("filename").as_string();
configuration::set_attribute("/shader/filename", std::make_shared<configuration_attribute>(filename));
}
#if defined(__EDITOR__)
void shader_configuration::deserialize(pugi::xml_node& node)
{
pugi::xml_attribute attribute;
attribute = node.append_attribute("filename");
std::string filename = shader_configuration::get_filename();
attribute.set_value(filename.c_str());
}
#endif
void shader_configuration::serialize(pugi::xml_document& document, pugi::xpath_node& node)
{
std::string filename = node.node().attribute("filename").as_string();
configuration::set_attribute("/shader/filename", std::make_shared<configuration_attribute>(filename));
}
}
