// autogenerated: do not add any changes
#ifndef shader_configuration_h
#define shader_configuration_h
#include "configuration.h"
namespace gb
{
class shader_configuration : public configuration
{
public:
shader_configuration(void) = default;
~shader_configuration(void) = default;
std::string get_filename(void) const;
#if defined(__EDITOR__)
void set_filename(std::string filename);
#endif
void serialize(pugi::xml_document& document, const std::string& path);
#if defined(__EDITOR__)
void deserialize(pugi::xml_node& node);
#endif
void serialize(pugi::xml_document& document, pugi::xpath_node& node);
};
};
#endif
