// autogenerated: do not add any changes
#include "shape_3d_configuration.h"
namespace gb
{
std::string shape_3d_configuration::get_mesh_filename(void) const
{
const auto& iterator = m_attributes.find("/shape_3d/mesh_filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void shape_3d_configuration::set_mesh_filename(std::string mesh_filename)
{
configuration::set_attribute("/shape_3d/mesh_filename", std::make_shared<configuration_attribute>(mesh_filename));
}
#endif
std::vector<std::shared_ptr<configuration>> shape_3d_configuration::get_materials_configurations(void) const
{
const auto& iterator = m_configurations.find("/shape_3d/materials/material");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void shape_3d_configuration::add_materials_configurations(const std::shared_ptr<gb::material_configuration>& material)
{
configuration::set_configuration("/shape_3d/materials/material", material);
}
#endif
#if defined(__IS_CONFIGURATION_MUTABLE__)
void shape_3d_configuration::set_materials_configurations(const std::shared_ptr<gb::material_configuration>& material, i32 index)
{
configuration::set_configuration("/shape_3d/materials/material", material, index);
}
#endif
std::vector<std::shared_ptr<configuration>> shape_3d_configuration::get_animations_configurations(void) const
{
const auto& iterator = m_configurations.find("/shape_3d/animations/animation");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void shape_3d_configuration::add_animations_configurations(const std::shared_ptr<gb::animation_3d_sequence_configuration>& animation)
{
configuration::set_configuration("/shape_3d/animations/animation", animation);
}
#endif
#if defined(__IS_CONFIGURATION_MUTABLE__)
void shape_3d_configuration::set_animations_configurations(const std::shared_ptr<gb::animation_3d_sequence_configuration>& animation, i32 index)
{
configuration::set_configuration("/shape_3d/animations/animation", animation, index);
}
#endif
void shape_3d_configuration::serialize_xml(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/shape_3d");
std::string mesh_filename = node.node().attribute("mesh_filename").as_string();
configuration::set_attribute("/shape_3d/mesh_filename", std::make_shared<configuration_attribute>(mesh_filename));
pugi::xpath_node_set material_nodes = document.select_nodes("/shape_3d/materials/material");
for (pugi::xpath_node_set::const_iterator iterator = material_nodes.begin(); iterator != material_nodes.end(); ++iterator)
{
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
std::string external_filename =(*iterator).node().attribute("filename").as_string();
if(external_filename.find(".xml") != std::string::npos)
{
material->serialize_xml(external_filename);
}
else if(external_filename.find(".json") != std::string::npos)
{
material->serialize_json(external_filename);
}
else
{
assert(false);
}
configuration::set_configuration("/shape_3d/materials/material", material);
}
pugi::xpath_node_set animation_nodes = document.select_nodes("/shape_3d/animations/animation");
for (pugi::xpath_node_set::const_iterator iterator = animation_nodes.begin(); iterator != animation_nodes.end(); ++iterator)
{
std::shared_ptr<gb::animation_3d_sequence_configuration> animation = std::make_shared<gb::animation_3d_sequence_configuration>();
pugi::xpath_node node = (*iterator);
animation->serialize_xml(document, node);
configuration::set_configuration("/shape_3d/animations/animation", animation);
}
}
void shape_3d_configuration::serialize_json(const std::string& filename)
{
Json::Value json;
bool result = configuration::open_json(json, filename);
assert(result);
std::string mesh_filename = json.get("mesh_filename", "unknown").asString();
configuration::set_attribute("/shape_3d/mesh_filename", std::make_shared<configuration_attribute>(mesh_filename));
Json::Value materials_json_array = json["materials"];
for (Json::ValueIterator iterator = materials_json_array.begin(); iterator != materials_json_array.end(); ++iterator)
{
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
Json::Value json_value = (*iterator);
std::string external_filename =json_value.get("filename", "unknown").asString();
if(external_filename.find(".xml") != std::string::npos)
{
material->serialize_xml(external_filename);
}
else if(external_filename.find(".json") != std::string::npos)
{
material->serialize_json(external_filename);
}
else
{
assert(false);
}
configuration::set_configuration("/shape_3d/materials/material", material);
}
Json::Value animations_json_array = json["animations"];
for (Json::ValueIterator iterator = animations_json_array.begin(); iterator != animations_json_array.end(); ++iterator)
{
std::shared_ptr<gb::animation_3d_sequence_configuration> animation = std::make_shared<gb::animation_3d_sequence_configuration>();
Json::Value json_value = (*iterator);
animation->serialize_json(json_value);
configuration::set_configuration("/shape_3d/animations/animation", animation);
}
}
}
