// autogenerated: do not add any changes
#ifndef ss_technique_configuration_h
#define ss_technique_configuration_h
#include "configuration.h"
#include "material_configuration.h"
namespace gb
{
class ss_technique_configuration : public configuration
{
public:
ss_technique_configuration(void) = default;
~ss_technique_configuration(void) = default;
std::string get_guid(void) const;
#if defined(__EDITOR__)
void set_guid(std::string guid);
#endif
ui32 get_screen_width(void) const;
#if defined(__EDITOR__)
void set_screen_width(ui32 screen_width);
#endif
ui32 get_screen_height(void) const;
#if defined(__EDITOR__)
void set_screen_height(ui32 screen_height);
#endif
std::shared_ptr<material_configuration> get_ConfigurationMaterial(void) const;
#if defined(__EDITOR__)
void set_ConfigurationMaterial(const std::shared_ptr<gb::material_configuration>& material);
#endif
void serialize(const std::string& filename);
#if defined(__EDITOR__)
void deserialize(const std::string& filename);
#endif
};
};
#endif
