// autogenerated: do not add any changes
#include "transition_configuration.h"
namespace gb
{
std::string transition_configuration::get_guid(void) const
{
const auto& iterator = m_attributes.find("/transition/guid");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__EDITOR__)
void transition_configuration::set_guid(std::string guid)
{
configuration::set_attribute("/transition/guid", std::make_shared<configuration_attribute>(guid));
}
#endif
std::shared_ptr<gb::output_technique_configuration> transition_configuration::get_output_technique_configuration(void) const
{
const auto& iterator = m_configurations.find("/transition/output_technique");
if(iterator == m_configurations.end())
{
return nullptr;
}
assert(iterator != m_configurations.end());
assert(iterator->second.size() != 0);
return std::static_pointer_cast<gb::output_technique_configuration>(iterator->second.at(0));
}
#if defined(__EDITOR__)
void transition_configuration::set_output_technique_configuration(const std::shared_ptr<gb::output_technique_configuration>& output_technique)
{
configuration::set_configuration("/transition/output_technique", output_technique, 0);
}
#endif
std::vector<std::shared_ptr<configuration>> transition_configuration::get_ws_technique_configuration(void) const
{
const auto& iterator = m_configurations.find("/transition/ws_techniques/ws_technique");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__EDITOR__)
void transition_configuration::add_ws_technique_configuration(const std::shared_ptr<gb::ws_technique_configuration>& ws_technique)
{
configuration::set_configuration("/transition/ws_techniques/ws_technique", ws_technique);
}
#endif
#if defined(__EDITOR__)
void transition_configuration::set_ws_technique_configuration(const std::shared_ptr<gb::ws_technique_configuration>& ws_technique, i32 index)
{
configuration::set_configuration("/transition/ws_techniques/ws_technique", ws_technique, index);
}
#endif
std::vector<std::shared_ptr<configuration>> transition_configuration::get_ss_technique_configuration(void) const
{
const auto& iterator = m_configurations.find("/transition/ss_techniques/ss_technique");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__EDITOR__)
void transition_configuration::add_ss_technique_configuration(const std::shared_ptr<gb::ss_technique_configuration>& ss_technique)
{
configuration::set_configuration("/transition/ss_techniques/ss_technique", ss_technique);
}
#endif
#if defined(__EDITOR__)
void transition_configuration::set_ss_technique_configuration(const std::shared_ptr<gb::ss_technique_configuration>& ss_technique, i32 index)
{
configuration::set_configuration("/transition/ss_techniques/ss_technique", ss_technique, index);
}
#endif
void transition_configuration::serialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml_document(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/transition");
std::string guid = node.node().attribute("guid").as_string();
configuration::set_attribute("/transition/guid", std::make_shared<configuration_attribute>(guid));
std::shared_ptr<gb::output_technique_configuration> output_technique = std::make_shared<gb::output_technique_configuration>();
pugi::xpath_node output_technique_node = document.select_single_node("/transition/output_technique");
output_technique->serialize(output_technique_node.node().attribute("filename").as_string());
configuration::set_configuration("/transition/output_technique", output_technique);
pugi::xpath_node_set ws_technique_nodes = document.select_nodes("/transition/ws_techniques/ws_technique");
for (pugi::xpath_node_set::const_iterator iterator = ws_technique_nodes.begin(); iterator != ws_technique_nodes.end(); ++iterator)
{
std::shared_ptr<gb::ws_technique_configuration> ws_technique = std::make_shared<gb::ws_technique_configuration>();
ws_technique->serialize((*iterator).node().attribute("filename").as_string());
configuration::set_configuration("/transition/ws_techniques/ws_technique", ws_technique);
}
pugi::xpath_node_set ss_technique_nodes = document.select_nodes("/transition/ss_techniques/ss_technique");
for (pugi::xpath_node_set::const_iterator iterator = ss_technique_nodes.begin(); iterator != ss_technique_nodes.end(); ++iterator)
{
std::shared_ptr<gb::ss_technique_configuration> ss_technique = std::make_shared<gb::ss_technique_configuration>();
ss_technique->serialize((*iterator).node().attribute("filename").as_string());
configuration::set_configuration("/transition/ss_techniques/ss_technique", ss_technique);
}
}
#if defined(__EDITOR__)
void transition_configuration::deserialize(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = document.load("");
assert(result.status == pugi::status_ok);
pugi::xml_node node = document.append_child("transition");
pugi::xml_node parent_node = node;
pugi::xml_attribute attribute;
attribute = node.append_attribute("guid");
std::string guid = transition_configuration::get_guid();
attribute.set_value(guid.c_str());
node = parent_node.append_child("output_technique");
attribute = node.append_attribute("filename");
attribute.set_value(configuration::get_filename().c_str());
node = parent_node.append_child("ws_techniques");
for(const auto& iterator : transition_configuration::get_ws_technique_configuration())
{
std::shared_ptr<gb::ws_technique_configuration> configuration = std::static_pointer_cast<gb::ws_technique_configuration>(iterator);
pugi::xml_node child_node = node.append_child("ws_technique");
attribute = child_node.append_attribute("filename");
attribute.set_value(configuration->get_filename().c_str());
}
node = parent_node.append_child("ss_techniques");
for(const auto& iterator : transition_configuration::get_ss_technique_configuration())
{
std::shared_ptr<gb::ss_technique_configuration> configuration = std::static_pointer_cast<gb::ss_technique_configuration>(iterator);
pugi::xml_node child_node = node.append_child("ss_technique");
attribute = child_node.append_attribute("filename");
attribute.set_value(configuration->get_filename().c_str());
}
document.save_file(filename.c_str());
}
#endif
}
