// autogenerated: do not add any changes
#ifndef car_progression_configuration_h
#define car_progression_configuration_h
#include "configuration.h"
namespace gb
{
class car_progression_configuration : public configuration
{
public:
car_progression_configuration(void) = default;
~car_progression_configuration(void) = default;
std::string get_car_filename(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_car_filename(std::string car_filename);
#endif
i32 get_car_id(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_car_id(i32 car_id);
#endif
i32 get_required_rank(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_required_rank(i32 required_rank);
#endif
i32 get_required_stars_for_next_rank(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_required_stars_for_next_rank(i32 required_stars_for_next_rank);
#endif
void serialize_xml(const std::string& filename);
void serialize_json(const std::string& filename);
};
};
#endif
