// autogenerated: do not add any changes
#include "cars_progression_configuration.h"
namespace gb
{
std::vector<std::shared_ptr<configuration>> cars_progression_configuration::get_cars_progression_configuration(void) const
{
const auto& iterator = m_configurations.find("/cars_progression/cars/car_progression");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void cars_progression_configuration::add_cars_progression_configuration(const std::shared_ptr<gb::car_progression_configuration>& car_progression)
{
configuration::set_configuration("/cars_progression/cars/car_progression", car_progression);
}
#endif
#if defined(__IS_CONFIGURATION_MUTABLE__)
void cars_progression_configuration::set_cars_progression_configuration(const std::shared_ptr<gb::car_progression_configuration>& car_progression, i32 index)
{
configuration::set_configuration("/cars_progression/cars/car_progression", car_progression, index);
}
#endif
void cars_progression_configuration::serialize_xml(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/cars_progression");
pugi::xpath_node_set car_progression_nodes = document.select_nodes("/cars_progression/cars/car_progression");
for (pugi::xpath_node_set::const_iterator iterator = car_progression_nodes.begin(); iterator != car_progression_nodes.end(); ++iterator)
{
std::shared_ptr<gb::car_progression_configuration> car_progression = std::make_shared<gb::car_progression_configuration>();
std::string external_filename =(*iterator).node().attribute("filename").as_string();
if(external_filename.find(".xml") != std::string::npos)
{
car_progression->serialize_xml(external_filename);
}
else if(external_filename.find(".json") != std::string::npos)
{
car_progression->serialize_json(external_filename);
}
else
{
assert(false);
}
configuration::set_configuration("/cars_progression/cars/car_progression", car_progression);
}
}
void cars_progression_configuration::serialize_json(const std::string& filename)
{
Json::Value json;
bool result = configuration::open_json(json, filename);
assert(result);
Json::Value car_progressions_json_array = json["cars"];
for (Json::ValueIterator iterator = car_progressions_json_array.begin(); iterator != car_progressions_json_array.end(); ++iterator)
{
std::shared_ptr<gb::car_progression_configuration> car_progression = std::make_shared<gb::car_progression_configuration>();
Json::Value json_value = (*iterator);
std::string external_filename =json_value.get("filename", "unknown").asString();
if(external_filename.find(".xml") != std::string::npos)
{
car_progression->serialize_xml(external_filename);
}
else if(external_filename.find(".json") != std::string::npos)
{
car_progression->serialize_json(external_filename);
}
else
{
assert(false);
}
configuration::set_configuration("/cars_progression/cars/car_progression", car_progression);
}
}
}
