// autogenerated: do not add any changes
#ifndef cell_configuration_h
#define cell_configuration_h
#include "configuration.h"
namespace gb
{
class cell_configuration : public configuration
{
public:
cell_configuration(void) = default;
~cell_configuration(void) = default;
std::string get_main_3d_configuration_filename(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_main_3d_configuration_filename(std::string main_3d_configuration_filename);
#endif
void serialize_xml(const std::string& filename);
void serialize_json(const std::string& filename);
};
};
#endif
