// autogenerated: do not add any changes, added changes will be lost.
#ifndef gameplay_configuration_accessor_h
#define gameplay_configuration_accessor_h
#include "character_configuration.h"
#include "mob_configuration.h"
namespace gb
{
class gameplay_configuration_accessor
{
public:
gameplay_configuration_accessor(void) = default;
~gameplay_configuration_accessor(void) = default;
std::shared_ptr<configuration> get_character_configuration(const std::string& filename) const;
std::shared_ptr<configuration> get_mob_configuration(const std::string& filename) const;
};
};
#endif
