// autogenerated: do not add any changes, added changes will be lost.
#include "gameplay_configuration_accessor.h"
namespace gb
{
std::shared_ptr<configuration> gameplay_configuration_accessor::get_character_configuration(const std::string& filename) const
{
std::shared_ptr<character_configuration> configuration = std::make_shared<character_configuration>();
if(filename.find(".xml") != std::string::npos)
{
configuration->serialize_xml(filename);
}
else if(filename.find(".json") != std::string::npos)
{
configuration->serialize_json(filename);
}
else
{
assert(false);
}
assert(configuration);
return configuration;
}
std::shared_ptr<configuration> gameplay_configuration_accessor::get_level_configuration(const std::string& filename) const
{
std::shared_ptr<level_configuration> configuration = std::make_shared<level_configuration>();
if(filename.find(".xml") != std::string::npos)
{
configuration->serialize_xml(filename);
}
else if(filename.find(".json") != std::string::npos)
{
configuration->serialize_json(filename);
}
else
{
assert(false);
}
assert(configuration);
return configuration;
}
std::shared_ptr<configuration> gameplay_configuration_accessor::get_mob_configuration(const std::string& filename) const
{
std::shared_ptr<mob_configuration> configuration = std::make_shared<mob_configuration>();
if(filename.find(".xml") != std::string::npos)
{
configuration->serialize_xml(filename);
}
else if(filename.find(".json") != std::string::npos)
{
configuration->serialize_json(filename);
}
else
{
assert(false);
}
assert(configuration);
return configuration;
}
}
