// autogenerated: do not add any changes
#ifndef level_configuration_h
#define level_configuration_h
#include "configuration.h"
namespace gb
{
class level_configuration : public configuration
{
public:
level_configuration(void) = default;
~level_configuration(void) = default;
std::string get_scene_filename(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_scene_filename(std::string scene_filename);
#endif
f32 get_complexity(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_complexity(f32 complexity);
#endif
f32 get_required_drift_time(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_required_drift_time(f32 required_drift_time);
#endif
i32 get_cars_count(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_cars_count(i32 cars_count);
#endif
i32 get_session_time_in_seconds(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_session_time_in_seconds(i32 session_time_in_seconds);
#endif
void serialize_xml(const std::string& filename);
void serialize_json(const std::string& filename);
};
};
#endif
