// autogenerated: do not add any changes
#ifndef levels_set_configuration_h
#define levels_set_configuration_h
#include "configuration.h"
#include "level_configuration.h"
namespace gb
{
class levels_set_configuration : public configuration
{
public:
levels_set_configuration(void) = default;
~levels_set_configuration(void) = default;
std::vector<std::shared_ptr<configuration>> get_levels_configuration(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void add_levels_configuration(const std::shared_ptr<gb::level_configuration>& level);
#endif
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_levels_configuration(const std::shared_ptr<gb::level_configuration>& level, i32 index);
#endif
void serialize_xml(const std::string& filename);
void serialize_json(const std::string& filename);
};
};
#endif
