// autogenerated: do not add any changes
#ifndef mob_configuration_h
#define mob_configuration_h
#include "configuration.h"
namespace gb
{
class mob_configuration : public configuration
{
public:
mob_configuration(void) = default;
~mob_configuration(void) = default;
std::string get_character_configuration_filename(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_character_configuration_filename(std::string character_configuration_filename);
#endif
f32 get_chase_start_distance(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_chase_start_distance(f32 chase_start_distance);
#endif
f32 get_chase_end_distance(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_chase_end_distance(f32 chase_end_distance);
#endif
void serialize_xml(const std::string& filename);
void serialize_json(const std::string& filename);
};
};
#endif
