// autogenerated: do not add any changes
#ifndef quest_dependency_configuration_h
#define quest_dependency_configuration_h
#include "configuration.h"
namespace gb
{
class quest_dependency_configuration : public configuration
{
public:
quest_dependency_configuration(void) = default;
~quest_dependency_configuration(void) = default;
i32 get_quest_id(void) const;
#if defined(__IS_CONFIGURATION_MUTABLE__)
void set_quest_id(i32 quest_id);
#endif
void serialize_xml(pugi::xml_document& document, const std::string& path);
void serialize_json(Json::Value& root);
void serialize_xml(pugi::xml_document& document, pugi::xpath_node& node);
};
};
#endif
