// autogenerated: do not add any changes, added changes will be lost.
#ifndef anim_configuration_accessor_h
#define anim_configuration_accessor_h
#include "animated_sprite_configuration.h"
namespace gb
{
class anim_configuration_accessor
{
public:
anim_configuration_accessor(void) = default;
~anim_configuration_accessor(void) = default;
std::shared_ptr<configuration> get_animated_sprite_configuration(const std::string& filename) const;
};
};
#endif
