// autogenerated: do not add any changes
#include "animated_sprite_configuration.h"
namespace gb
{
std::string animated_sprite_configuration::get_animation_filename(void) const
{
const auto& iterator = m_attributes.find("/animated_sprite/animation_filename");
assert(iterator != m_attributes.end());
std::string value; iterator->second->get(&value);
return value;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void animated_sprite_configuration::set_animation_filename(std::string animation_filename)
{
configuration::set_attribute("/animated_sprite/animation_filename", std::make_shared<configuration_attribute>(animation_filename));
}
#endif
std::vector<std::shared_ptr<configuration>> animated_sprite_configuration::get_materials_configurations(void) const
{
const auto& iterator = m_configurations.find("/animated_sprite/materials/material");
if(iterator == m_configurations.end())
{
return std::vector<std::shared_ptr<configuration>>();
}
assert(iterator != m_configurations.end());
return iterator->second;
}
#if defined(__IS_CONFIGURATION_MUTABLE__)
void animated_sprite_configuration::add_materials_configurations(const std::shared_ptr<gb::material_configuration>& material)
{
configuration::set_configuration("/animated_sprite/materials/material", material);
}
#endif
#if defined(__IS_CONFIGURATION_MUTABLE__)
void animated_sprite_configuration::set_materials_configurations(const std::shared_ptr<gb::material_configuration>& material, i32 index)
{
configuration::set_configuration("/animated_sprite/materials/material", material, index);
}
#endif
void animated_sprite_configuration::serialize_xml(const std::string& filename)
{
pugi::xml_document document;
pugi::xml_parse_result result = configuration::open_xml(document, filename);
assert(result.status == pugi::status_ok);
pugi::xpath_node node;
node = document.select_single_node("/animated_sprite");
std::string animation_filename = node.node().attribute("animation_filename").as_string();
configuration::set_attribute("/animated_sprite/animation_filename", std::make_shared<configuration_attribute>(animation_filename));
pugi::xpath_node_set material_nodes = document.select_nodes("/animated_sprite/materials/material");
for (pugi::xpath_node_set::const_iterator iterator = material_nodes.begin(); iterator != material_nodes.end(); ++iterator)
{
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
std::string external_filename =(*iterator).node().attribute("filename").as_string();
if(external_filename.find(".xml") != std::string::npos)
{
material->serialize_xml(external_filename);
}
else if(external_filename.find(".json") != std::string::npos)
{
material->serialize_json(external_filename);
}
else
{
assert(false);
}
configuration::set_configuration("/animated_sprite/materials/material", material);
}
}
void animated_sprite_configuration::serialize_json(const std::string& filename)
{
Json::Value json;
bool result = configuration::open_json(json, filename);
assert(result);
std::string animation_filename = json.get("animation_filename", "unknown").asString();
configuration::set_attribute("/animated_sprite/animation_filename", std::make_shared<configuration_attribute>(animation_filename));
Json::Value materials_json_array = json["materials"];
for (Json::ValueIterator iterator = materials_json_array.begin(); iterator != materials_json_array.end(); ++iterator)
{
std::shared_ptr<gb::material_configuration> material = std::make_shared<gb::material_configuration>();
Json::Value json_value = (*iterator);
std::string external_filename =json_value.get("filename", "unknown").asString();
if(external_filename.find(".xml") != std::string::npos)
{
material->serialize_xml(external_filename);
}
else if(external_filename.find(".json") != std::string::npos)
{
material->serialize_json(external_filename);
}
else
{
assert(false);
}
configuration::set_configuration("/animated_sprite/materials/material", material);
}
}
}
