# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'gbDemo-ios' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gbDemo-ios

pod 'Firebase/Core'
pod 'Firebase/AdMob'
pod 'Firebase/Firestore'
pod 'Fabric'
pod 'Crashlytics'

end

target 'gbDemo-osx' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gbDemo-osx

pod 'Firebase/Core'
pod 'Firebase/Firestore'
pod 'Fabric'
pod 'Crashlytics'

end

target 'gbDemo-tvos' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for gbDemo-tvos

end
